# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\N_modules_Window_1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NModulesWindow1(object):
    def setupUi(self, NModulesWindow1):
        NModulesWindow1.setObjectName("NModulesWindow1")
        NModulesWindow1.resize(401, 312)
        NModulesWindow1.setStyleSheet("background-color: white")
        self.frame = QtWidgets.QFrame(NModulesWindow1)
        self.frame.setGeometry(QtCore.QRect(0, 20, 401, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: white")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.line_n1 = QtWidgets.QLineEdit(self.frame)
        self.line_n1.setGeometry(QtCore.QRect(20, 70, 171, 22))
        self.line_n1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_n1.setStyleSheet("background-color: #00D5FF;")
        self.line_n1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_n1.setObjectName("line_n1")
        self.line_n2 = QtWidgets.QLineEdit(self.frame)
        self.line_n2.setGeometry(QtCore.QRect(210, 70, 171, 22))
        self.line_n2.setStyleSheet("background-color: #00D5FF;")
        self.line_n2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_n2.setObjectName("line_n2")
        self.operations = QtWidgets.QComboBox(self.frame)
        self.operations.setGeometry(QtCore.QRect(60, 160, 281, 31))
        self.operations.setStyleSheet("background-color: #00D5FF;")
        self.operations.setObjectName("operations")
        self.operations.addItem("")
        self.operations.addItem("")
        self.operations.addItem("")
        self.operations.addItem("")
        self.operations.addItem("")
        self.operations.addItem("")
        self.operations.addItem("")
        self.operations.addItem("")
        self.operations.addItem("")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 110, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 200, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.result = QtWidgets.QLabel(self.frame)
        self.result.setGeometry(QtCore.QRect(10, 240, 371, 31))
        self.result.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result.setStyleSheet("background-color: #00D5FF;")
        self.result.setFrameShape(QtWidgets.QFrame.Box)
        self.result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result.setObjectName("result")
        self.pushButton_return = QtWidgets.QToolButton(NModulesWindow1)
        self.pushButton_return.setGeometry(QtCore.QRect(0, 0, 51, 22))
        self.pushButton_return.setStyleSheet("color: #00D5FF")
        self.pushButton_return.setObjectName("pushButton_return")

        self.retranslateUi(NModulesWindow1)
        QtCore.QMetaObject.connectSlotsByName(NModulesWindow1)

    def retranslateUi(self, NModulesWindow1):
        _translate = QtCore.QCoreApplication.translate
        NModulesWindow1.setWindowTitle(_translate("NModulesWindow1", "Основные бинарные операции"))
        self.label_3.setText(_translate("NModulesWindow1", "Введите 2 натуральных числа:"))
        self.line_n1.setText(_translate("NModulesWindow1", "0"))
        self.line_n2.setText(_translate("NModulesWindow1", "0"))
        self.operations.setItemText(0, _translate("NModulesWindow1", "Сравнение"))
        self.operations.setItemText(1, _translate("NModulesWindow1", "Сумма"))
        self.operations.setItemText(2, _translate("NModulesWindow1", "Разность"))
        self.operations.setItemText(3, _translate("NModulesWindow1", "Произведение"))
        self.operations.setItemText(4, _translate("NModulesWindow1", "Первая цифра частного"))
        self.operations.setItemText(5, _translate("NModulesWindow1", "Частное от деления"))
        self.operations.setItemText(6, _translate("NModulesWindow1", "Остаток от деления"))
        self.operations.setItemText(7, _translate("NModulesWindow1", "НОД"))
        self.operations.setItemText(8, _translate("NModulesWindow1", "НОК"))
        self.label.setText(_translate("NModulesWindow1", "Выберите действие:"))
        self.label_2.setText(_translate("NModulesWindow1", "Результат:"))
        self.result.setText(_translate("NModulesWindow1", "0"))
        self.pushButton_return.setText(_translate("NModulesWindow1", "<-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NModulesWindow1 = QtWidgets.QDialog()
    ui = Ui_NModulesWindow1()
    ui.setupUi(NModulesWindow1)
    NModulesWindow1.show()
    sys.exit(app.exec_())

