# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\P_modules_Window_1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PModulesWindow1(object):
    def setupUi(self, PModulesWindow1):
        PModulesWindow1.setObjectName("PModulesWindow1")
        PModulesWindow1.resize(400, 336)
        self.frame = QtWidgets.QFrame(PModulesWindow1)
        self.frame.setGeometry(QtCore.QRect(0, 20, 401, 311))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: white")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.operation = QtWidgets.QComboBox(self.frame)
        self.operation.setGeometry(QtCore.QRect(70, 180, 281, 31))
        self.operation.setStyleSheet("color: white; background-color: #0D66FF;")
        self.operation.setObjectName("operation")
        self.operation.addItem("")
        self.operation.addItem("")
        self.operation.addItem("")
        self.operation.addItem("")
        self.operation.addItem("")
        self.operation.addItem("")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 130, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 220, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.result = QtWidgets.QLabel(self.frame)
        self.result.setGeometry(QtCore.QRect(10, 260, 371, 31))
        self.result.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result.setStyleSheet("color: white; background-color: #0D66FF;")
        self.result.setFrameShape(QtWidgets.QFrame.Box)
        self.result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result.setObjectName("result")
        self.polinomial1 = QtWidgets.QLabel(self.frame)
        self.polinomial1.setGeometry(QtCore.QRect(10, 50, 311, 31))
        self.polinomial1.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.polinomial1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.polinomial1.setStyleSheet("color: white; background-color: #0D66FF;")
        self.polinomial1.setFrameShape(QtWidgets.QFrame.Box)
        self.polinomial1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.polinomial1.setObjectName("polinomial1")
        self.polinomial2 = QtWidgets.QLabel(self.frame)
        self.polinomial2.setGeometry(QtCore.QRect(10, 90, 311, 31))
        self.polinomial2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.polinomial2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.polinomial2.setStyleSheet("color: white; background-color: #0D66FF;")
        self.polinomial2.setFrameShape(QtWidgets.QFrame.Box)
        self.polinomial2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.polinomial2.setObjectName("polinomial2")
        self.pushButton_inputp1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_inputp1.setGeometry(QtCore.QRect(330, 50, 51, 28))
        self.pushButton_inputp1.setStyleSheet("color: white; background-color: #0D66FF;")
        self.pushButton_inputp1.setObjectName("pushButton_inputp1")
        self.pushButton_inputp2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_inputp2.setGeometry(QtCore.QRect(330, 90, 51, 28))
        self.pushButton_inputp2.setStyleSheet("color: white; background-color: #0D66FF;")
        self.pushButton_inputp2.setObjectName("pushButton_inputp2")
        self.pushButton_return = QtWidgets.QToolButton(PModulesWindow1)
        self.pushButton_return.setGeometry(QtCore.QRect(0, 0, 27, 22))
        self.pushButton_return.setStyleSheet("color: white; background-color: #0D66FF;")
        self.pushButton_return.setObjectName("pushButton_return")

        self.retranslateUi(PModulesWindow1)
        QtCore.QMetaObject.connectSlotsByName(PModulesWindow1)

    def retranslateUi(self, PModulesWindow1):
        _translate = QtCore.QCoreApplication.translate
        PModulesWindow1.setWindowTitle(_translate("PModulesWindow1", "Основные бинарные операции"))
        self.label_3.setText(_translate("PModulesWindow1", "Введите 2 многочлена:"))
        self.operation.setItemText(0, _translate("PModulesWindow1", "Сумма"))
        self.operation.setItemText(1, _translate("PModulesWindow1", "Разность"))
        self.operation.setItemText(2, _translate("PModulesWindow1", "Произведение"))
        self.operation.setItemText(3, _translate("PModulesWindow1", "Частное от деления"))
        self.operation.setItemText(4, _translate("PModulesWindow1", "Остаток от деления"))
        self.operation.setItemText(5, _translate("PModulesWindow1", "НОД"))
        self.label.setText(_translate("PModulesWindow1", "Выберите действие:"))
        self.label_2.setText(_translate("PModulesWindow1", "Результат:"))
        self.result.setText(_translate("PModulesWindow1", "0"))
        self.polinomial1.setText(_translate("PModulesWindow1", "0"))
        self.polinomial2.setText(_translate("PModulesWindow1", "0"))
        self.pushButton_inputp1.setText(_translate("PModulesWindow1", "Ввести"))
        self.pushButton_inputp2.setText(_translate("PModulesWindow1", "Ввести"))
        self.pushButton_return.setText(_translate("PModulesWindow1", "<-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PModulesWindow1 = QtWidgets.QDialog()
    ui = Ui_PModulesWindow1()
    ui.setupUi(PModulesWindow1)
    PModulesWindow1.show()
    sys.exit(app.exec_())

