# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\P_modules_Window_3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PModulesWindow3(object):
    def setupUi(self, PModulesWindow3):
        PModulesWindow3.setObjectName("PModulesWindow3")
        PModulesWindow3.resize(400, 347)
        self.frame = QtWidgets.QFrame(PModulesWindow3)
        self.frame.setGeometry(QtCore.QRect(0, 20, 401, 321))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: white")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.operation = QtWidgets.QComboBox(self.frame)
        self.operation.setGeometry(QtCore.QRect(60, 200, 281, 31))
        self.operation.setStyleSheet("color: white; background-color: #0D66FF;")
        self.operation.setObjectName("operation")
        self.operation.addItem("")
        self.operation.addItem("")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 160, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 240, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.result = QtWidgets.QLabel(self.frame)
        self.result.setGeometry(QtCore.QRect(10, 280, 371, 31))
        self.result.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result.setStyleSheet("color: white; background-color: #0D66FF;")
        self.result.setFrameShape(QtWidgets.QFrame.Box)
        self.result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result.setObjectName("result")
        self.polinomial = QtWidgets.QLabel(self.frame)
        self.polinomial.setGeometry(QtCore.QRect(10, 60, 311, 31))
        self.polinomial.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.polinomial.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.polinomial.setStyleSheet("color: white; background-color: #0D66FF;")
        self.polinomial.setFrameShape(QtWidgets.QFrame.Box)
        self.polinomial.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.polinomial.setObjectName("polinomial")
        self.pushButton_inputp = QtWidgets.QPushButton(self.frame)
        self.pushButton_inputp.setGeometry(QtCore.QRect(330, 60, 51, 28))
        self.pushButton_inputp.setStyleSheet("color: white; background-color: #0D66FF;")
        self.pushButton_inputp.setObjectName("pushButton_inputp")
        self.line_qm = QtWidgets.QLineEdit(self.frame)
        self.line_qm.setGeometry(QtCore.QRect(10, 100, 311, 22))
        self.line_qm.setStyleSheet("color: white; background-color: #0D66FF;")
        self.line_qm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_qm.setObjectName("line_qm")
        self.lind_d = QtWidgets.QLineEdit(self.frame)
        self.lind_d.setEnabled(False)
        self.lind_d.setGeometry(QtCore.QRect(340, 110, 41, 21))
        self.lind_d.setStyleSheet("color: white; background-color: #0D66FF;")
        self.lind_d.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lind_d.setObjectName("lind_d")
        self.line_qn = QtWidgets.QLineEdit(self.frame)
        self.line_qn.setGeometry(QtCore.QRect(10, 130, 311, 22))
        self.line_qn.setStyleSheet("color: white; background-color: #0D66FF;")
        self.line_qn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_qn.setObjectName("line_qn")
        self.pushButton_return = QtWidgets.QToolButton(PModulesWindow3)
        self.pushButton_return.setGeometry(QtCore.QRect(0, 0, 27, 22))
        self.pushButton_return.setStyleSheet("color: white; background-color: #0D66FF;")
        self.pushButton_return.setObjectName("pushButton_return")

        self.retranslateUi(PModulesWindow3)
        QtCore.QMetaObject.connectSlotsByName(PModulesWindow3)

    def retranslateUi(self, PModulesWindow3):
        _translate = QtCore.QCoreApplication.translate
        PModulesWindow3.setWindowTitle(_translate("PModulesWindow3", "Прочие действия"))
        self.label_3.setText(_translate("PModulesWindow3", "Введите многочлен и число:"))
        self.operation.setItemText(0, _translate("PModulesWindow3", "Умножение на число"))
        self.operation.setItemText(1, _translate("PModulesWindow3", "Умножение на x^k"))
        self.label.setText(_translate("PModulesWindow3", "Выберите действие:"))
        self.label_2.setText(_translate("PModulesWindow3", "Результат:"))
        self.result.setText(_translate("PModulesWindow3", "0"))
        self.polinomial.setText(_translate("PModulesWindow3", "0"))
        self.pushButton_inputp.setText(_translate("PModulesWindow3", "Ввести"))
        self.line_qm.setText(_translate("PModulesWindow3", "0"))
        self.lind_d.setText(_translate("PModulesWindow3", "0"))
        self.line_qn.setText(_translate("PModulesWindow3", "1"))
        self.pushButton_return.setText(_translate("PModulesWindow3", "<-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PModulesWindow3 = QtWidgets.QDialog()
    ui = Ui_PModulesWindow3()
    ui.setupUi(PModulesWindow3)
    PModulesWindow3.show()
    sys.exit(app.exec_())

