# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Z_modules_Window_1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ZModulesWindow1(object):
    def setupUi(self, ZModulesWindow1):
        ZModulesWindow1.setObjectName("ZModulesWindow1")
        ZModulesWindow1.resize(406, 313)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ZModulesWindow1.sizePolicy().hasHeightForWidth())
        ZModulesWindow1.setSizePolicy(sizePolicy)
        self.frame = QtWidgets.QFrame(ZModulesWindow1)
        self.frame.setGeometry(QtCore.QRect(0, 20, 401, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: white")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.line_n1 = QtWidgets.QLineEdit(self.frame)
        self.line_n1.setGeometry(QtCore.QRect(20, 70, 171, 22))
        self.line_n1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_n1.setStyleSheet("background-color: #2EE800;")
        self.line_n1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_n1.setObjectName("line_n1")
        self.line_n2 = QtWidgets.QLineEdit(self.frame)
        self.line_n2.setGeometry(QtCore.QRect(210, 70, 171, 22))
        self.line_n2.setStyleSheet("background-color: #2EE800;")
        self.line_n2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_n2.setObjectName("line_n2")
        self.operations = QtWidgets.QComboBox(self.frame)
        self.operations.setGeometry(QtCore.QRect(70, 160, 281, 31))
        self.operations.setStyleSheet("background-color: #2EE800;")
        self.operations.setObjectName("operations")
        self.operations.addItem("")
        self.operations.addItem("")
        self.operations.addItem("")
        self.operations.addItem("")
        self.operations.addItem("")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 110, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: white")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 200, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.result = QtWidgets.QLabel(self.frame)
        self.result.setGeometry(QtCore.QRect(10, 240, 371, 31))
        self.result.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result.setStyleSheet("background-color: #2EE800;")
        self.result.setFrameShape(QtWidgets.QFrame.Box)
        self.result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result.setObjectName("result")
        self.pushButton_return = QtWidgets.QToolButton(ZModulesWindow1)
        self.pushButton_return.setGeometry(QtCore.QRect(0, 0, 27, 22))
        self.pushButton_return.setStyleSheet("background-color: #2EE800;")
        self.pushButton_return.setObjectName("pushButton_return")

        self.retranslateUi(ZModulesWindow1)
        QtCore.QMetaObject.connectSlotsByName(ZModulesWindow1)

    def retranslateUi(self, ZModulesWindow1):
        _translate = QtCore.QCoreApplication.translate
        ZModulesWindow1.setWindowTitle(_translate("ZModulesWindow1", "Основные бинарный операции"))
        self.label_3.setText(_translate("ZModulesWindow1", "Введите 2 целых числа:"))
        self.line_n1.setText(_translate("ZModulesWindow1", "0"))
        self.line_n2.setText(_translate("ZModulesWindow1", "0"))
        self.operations.setItemText(0, _translate("ZModulesWindow1", "Сумма"))
        self.operations.setItemText(1, _translate("ZModulesWindow1", "Разность"))
        self.operations.setItemText(2, _translate("ZModulesWindow1", "Произведение"))
        self.operations.setItemText(3, _translate("ZModulesWindow1", "Частное от деления"))
        self.operations.setItemText(4, _translate("ZModulesWindow1", "Остаток от деления"))
        self.label.setText(_translate("ZModulesWindow1", "Выберите действие:"))
        self.label_2.setText(_translate("ZModulesWindow1", "Результат:"))
        self.result.setText(_translate("ZModulesWindow1", "0"))
        self.pushButton_return.setText(_translate("ZModulesWindow1", "<-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ZModulesWindow1 = QtWidgets.QDialog()
    ui = Ui_ZModulesWindow1()
    ui.setupUi(ZModulesWindow1)
    ZModulesWindow1.show()
    sys.exit(app.exec_())

